version: '3.3'
services:
  web:
    container_name: data_filter
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - API_URL=${API_URL}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - TEMPLATES_DIR=/templates
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SFTP_SERVER=${SFTP_SERVER}
      - SFTP_USERNAME=${SFTP_USERNAME}
      - SFTP_PRIVATE_KEY_PATH=${SFTP_PRIVATE_KEY_PATH}
      - SFTP_REMOTE_PATH=${SFTP_REMOTE_PATH}
    volumes:
      - shared_tmp:/tmp/shared
    networks:
      datafilter_network:
        ipv4_address: 172.23.0.2


    depends_on:
      - rabbitmq
      - postgres
      - redis

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_app worker --loglevel=info
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - TEMPLATES_DIR=/templates
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SFTP_SERVER=${SFTP_SERVER}
      - SFTP_USERNAME=${SFTP_USERNAME}
      - SFTP_PRIVATE_KEY_PATH=${SFTP_PRIVATE_KEY_PATH}
      - SFTP_REMOTE_PATH=${SFTP_REMOTE_PATH}
    volumes:
      - shared_tmp:/tmp/shared
    networks:
      datafilter_network:
        ipv4_address: 172.23.0.3
      
    depends_on:
      - rabbitmq
      - postgres
      - redis

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    networks:
      datafilter_network:
        ipv4_address: 172.23.0.4

  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      datafilter_network:
        ipv4_address: 172.23.0.5

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      datafilter_network:
        ipv4_address: 172.23.0.6

networks:
  datafilter_network:
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1

volumes:
  shared_tmp:
  db_data:
