version: '3.3'
services:
  web:
    container_name: data_filter
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - TEMPLATES_DIR=/templates
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SFTP_SERVER=${SFTP_SERVER}
      - SFTP_USERNAME=${SFTP_USERNAME}
      - SFTP_PRIVATE_KEY_PATH=${SFTP_PRIVATE_KEY_PATH}
      - SFTP_REMOTE_PATH=${SFTP_REMOTE_PATH}
    volumes:
      - .:/app
      - shared_tmp:/tmp/shared
      - ./ssh:/app/ssh:ro

    depends_on:
      - rabbitmq
      - postgres
      - redis

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_app worker --loglevel=info
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - TEMPLATES_DIR=/templates
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SFTP_SERVER=${SFTP_SERVER}
      - SFTP_USERNAME=${SFTP_USERNAME}
      - SFTP_PRIVATE_KEY_PATH=${SFTP_PRIVATE_KEY_PATH}
      - SFTP_REMOTE_PATH=${SFTP_REMOTE_PATH}
    volumes:
      - .:/app
      - shared_tmp:/tmp/shared
      
    depends_on:
      - rabbitmq
      - postgres
      - redis

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


  redis:
    container_name: redis
    image: redis:alpine



volumes:
  shared_tmp:
